2025-07-04 19:44:17,735: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2025-07-04 19:44:17,735: [11] m.main:INFO: Beginning analysis
2025-07-04 19:44:17,737: [11] m.e.manticore:INFO: Starting symbolic create contract
2025-07-04 19:44:18,098: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2025-07-04 19:44:19,136: [11] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-07-04 19:44:19,146: [11] m.e.manticore:INFO: 0 alive states, 0 terminated states
2025-07-04 19:44:19,200: [11] m.c.manticore:INFO: Results in /mcore_tjas2yt6
2025-07-04 19:44:19,201: [11] m.c.manticore:INFO: Total time: 1.0989775657653809
