WARNING:root:You are using solc version 0.4.26. The supported version is 0.4.21.
INFO:root:Contract /sb/0x715a3a95cf9431cb9141040ee280b3d38cf3346d.sol:Bbay:
INFO:symExec:Running, please wait...

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


!!! SYMBOLIC EXECUTION TIMEOUT !!!
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/root/osiris/z3/z3.py", line 137, in z3_error_handler
    def z3_error_handler(c, e):
  File "/root/osiris/symExec.py", line 2868, in handler
    raise Exception("timeout")
Exception: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 73.1%
INFO:symExec:	  Arithmetic bugs: 	 False
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 16.0767748356 seconds ---
INFO:symExec:	====== Analysis Completed ======
INFO:root:Contract /sb/0x715a3a95cf9431cb9141040ee280b3d38cf3346d.sol:SafeMath:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 100.0%
INFO:symExec:	  Arithmetic bugs: 	 False
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 0.008544921875 seconds ---
INFO:symExec:	====== Analysis Completed ======
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored

