WARNING:root:You are using solc version 0.4.26. The supported version is 0.4.21.
INFO:root:Contract /sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:LogFile:
INFO:symExec:Running, please wait...
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 425, in propagate_taint
    if arithmetic_error["instruction"].data_in[0] == 32 or arithmetic_error["instruction"].data_in[1] == 32:
  File "/root/osiris/z3/z3.py", line 302, in __nonzero__
    return self.__bool__()
  File "/root/osiris/z3/z3.py", line 309, in __bool__
    elif is_eq(self) and self.num_args() == 2:
  File "/root/osiris/z3/z3.py", line 1422, in is_eq
    return is_app_of(a, Z3_OP_EQ)
  File "/root/osiris/z3/z3.py", line 1164, in is_app_of
    return is_app(a) and a.decl().kind() == k
  File "/root/osiris/z3/z3.py", line 885, in decl
    return FuncDeclRef(Z3_get_app_decl(self.ctx_ref(), self.as_ast()), self.ctx)
  File "/root/osiris/z3/z3.py", line 280, in __init__
    Z3_inc_ref(self.ctx.ref(), self.as_ast())
  File "/root/osiris/z3/z3core.py", line 1368, in Z3_inc_ref
    _elems.f(a0, a1)
  File "/root/osiris/symExec.py", line 2868, in handler
    raise Exception("timeout")
Exception: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 55.7%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 True
/sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:LogFile:2:21
n.io 
^
/sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:LogFile:94:9
History.push(LastMsg)
^
INFO:symExec:	  └> Underflow bugs: 	 True
/sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:LogFile:94:9
History.push(LastMsg)
^
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 12.0440781116 seconds ---
INFO:symExec:	====== Analysis Completed ======
INFO:root:Contract /sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:PERSONAL_BANK:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 99.9%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 True
/sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:PERSONAL_BANK:43:9
balances[msg.sender]+= msg.value
^
INFO:symExec:	  └> Underflow bugs: 	 True
/sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:PERSONAL_BANK:56:17
balances[msg.sender]-=_am
^
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 True
/sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:PERSONAL_BANK:54:16
msg.sender.call.value(_am)()
^
/sb/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol:PERSONAL_BANK:57:17
Log.AddMessage(msg.sender,_am,"Collect")
^
INFO:symExec:	 --- 2.2708439827 seconds ---
INFO:symExec:	====== Analysis Completed ======

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


!!! SYMBOLIC EXECUTION TIMEOUT !!!
Unexpected error: <type 'exceptions.Exception'>

