Exception in time_manipulation,unchecked_ll_calls module
Traceback (most recent call last):
  File "/conkas/vuln_finder/vulnerability_finder.py", line 51, in __analyse_modules
    vulns = vuln_finder.available_modules[vuln_module_key](self._traces, self._find_all)
KeyError: 'time_manipulation,unchecked_ll_calls'
Exception in time_manipulation,unchecked_ll_calls module
Traceback (most recent call last):
  File "/conkas/vuln_finder/vulnerability_finder.py", line 51, in __analyse_modules
    vulns = vuln_finder.available_modules[vuln_module_key](self._traces, self._find_all)
KeyError: 'time_manipulation,unchecked_ll_calls'
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
Analysing /sb/0x820ff8ccf3e70070cc742db2d64b124d83fcfa76.sol:GenericToken...
Analysing /sb/0x820ff8ccf3e70070cc742db2d64b124d83fcfa76.sol:StandardToken...
Analysing /sb/0x820ff8ccf3e70070cc742db2d64b124d83fcfa76.sol:Token...
Nothing to analyse
